[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-optional"

[build]
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200